### PR TITLE
CreateAdditionalFieldsForHbzPublishingCatalogue

### PR DESCRIPTION
**Pull request by TobiasNx**
Based on https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=949911658

### CODE REVIEW

**Comment by pkiraly** [comment]
@TobiasNx I saw that you closed this PR. I see that it contains a mix of things, some a quite good, some are not, and there are parts which requires further discussion. I suggest to create a new PR for the hbz MARC's package.

**Comment by TobiasNx** [comment]
Yes, @pkiraly this is a PR for https://github.com/hbz/qa-catalogue. See also: https://github.com/hbz/qa-catalogue/pull/1

I opened the PR on the wrong remote.

It should only contain the last three commits.

**Comment by nichtich** [comment]
Thanks a lot for contribution. This mixes several issues and should better be split into individual commits to be merged independently:

- Introduction of environment variable `JAVA_OPTIONS` (needs to be documented in README.md)
- Change of `Dockerfile` and `docker-compose.yml` (either remove/change lines or keep them but don't just comment out lines!) this also changes a default port, so it might break things!
- Additional MARC Field classes for custom fields (unfortunately MARC validation does not make use of Avram file yet, otherwise this would not be needed)
- Additional catalogue `oersi`
- Additional catalogue `test` (great to have tests, this should be used for CI!
- Add `hbz` scripts (I doubt this is the right place to host them)
- PHP classes `web-classes` - these don't belong here but into https://github.com/pkiraly/qa-catalogue-web and should be [replaced with non-executable configuration files](https://github.com/pkiraly/qa-catalogue-web/issues/108) anyway!
- last but not least `web-config/configuration.cnf` seems to be slipped though from your local configuration.

**Comment by TobiasNx** [comment]
@nichtich the PR was not intended for  `pkiraly:main` [hbz/qa-catalogue](https://github.com/hbz/qa-catalogue). Contribution on the main project will be provided by @Phu2 when he is ready. Therefore i closed it. 

But thanks for the systematic analysis.

**Pull request closed without merging**
