### PR TITLE
Remove last non-Avram keys from exported schema

### PR DESCRIPTION
**Pull request by nichtich**

### CODE REVIEW

**Comment by pkiraly** [comment]
@nichtich I am fine with removing unitLenght, but I would like to keep the repeatableContent flag at least wehn it is true. We can remove it when it is false (because that is the normal case). Could you imagine to put repeatableContent to Avram schema?

**Comment by nichtich** [comment]
I hesitate to add more cases and rules to core Avram, especially when there are alternatives. Adding `repeatableContent` would require to clearly define its semantics. How about an alternative to `codes` for repeatable elements: 

~~~json
{
  "positions":{
    "01-04":{
      "label":"Illustrations",
      "url":"https://www.loc.gov/marc/bibliographic/bd006.html",
      "flags": {  ← like codes but repeatable to fill length of 4 characters
        " ":{"label":"No illustrations"}, ← length of flag (here 1 for " ") must be proper divisor of 4
        "a":{"label":"Illustrations"},
        "b":{"label":"Maps"},
~~~

**Comment by pkiraly** [comment]
I am fine with this solution, so you can go further with it in this PR. 
I have however some concerns that potential future users of Avram will find it a bit confusing that same thing have different names.

**Comment by pkiraly** [comment]
I adjusted the UNIMARC schema reader to adapt the current changes (`flags` and `codelist`).

**Comment by pkiraly** [comment]
@nichtich What is the status of this PR? You wrote „I'm extending the pull request to also solve #402”  but there were no more commits after this comment.

**Comment by nichtich** [comment]
Thanks for reminder. I directly committed to the main branch with an update.

**Pull request closed without merging**
